### PR TITLE
Add travis CI config

### PR DESCRIPTION
**Pull request by sgeisler**
If you activate builds for this repository travis will automatically build and run the tests on every push and PR. It will look like [this](https://travis-ci.org/sgeisler/rust-bech32/builds/350752402). And we will be able to add these nice badges to the README.md [Build Status](https://travis-ci.org/sgeisler/rust-bech32).

### CODE REVIEW

**Comment by clarkmoody** [comment]
Rebase to `master` for a quick merge?

**Comment by sgeisler** [comment]
I can do that, but what is the benefit if there are no conflicts?

**Comment by clarkmoody** [comment]
Thanks. Rebase creates a cleaner network graph, for a more logical understanding of the repo's history.

**Comment by sgeisler** [comment]
@clarkmoody for travis CI to work you have to activate it for this repo ([short howto](https://docs.travis-ci.com/user/getting-started/)). It would be nice if you could do this :)

**Pull request merged**
